# LinShare parameters
linshare:

  # General settings for Linshare's back-end
  backend:
    image: "docker-registry.linagora.com:5000/linshare-snapshots/linshare-backend:4.0.0"

    # Memory management
    javaXmx: 2048m
    resources:
      limits:
        cpu: "4"
        memory: "4Gi"
      requests:
        cpu: "2"
        memory: "2Gi"

    # Miscellaneous
    profiles: default,jcloud,batches
    ssoIpFilter: false
    extraProperties: []
    ldapHost: linshare-ldap

    # Storage
    storage:
      # Store on a disk (filesystem) or in a bucket (openstack-swift)
      mode: openstack-swift
      # The directory where to store files, IF stored on a file system
      directory: /var/lib/linshare/filesystemstorage
      # Options for the bucket storage (Swift) are defined as a secret

    # Local storage (seen as a volume in the POD, to store temporary files)
    localCache:
      storageSize: 20Gi
      storageClass: cinder-high-speed

    # SMTP
    smtp:
      host: linshare-demo-mail
      port: "25"
      enableAuth: false
      enableSsl: false
      enableTls: false

  # Configuration for Linshare's administration
  uiAdmin:
    image: "docker-registry.linagora.com:5000/linshare-snapshots/linshare-ui-admin:4.0.0"
    url: null

  # Configuration for LinShare's UI
  uiUser:
    image: "docker-registry.linagora.com:5000/linshare-snapshots/linshare-ui-user:4.0.0"
    url: null
    externalUrl: null
    replicaCount: 1

  # LinShare's initialization
  init:
    image: "docker-registry.linagora.com:5000/linshare-releases/linshare-init:4.0.0"
    noReply: no-reply@linshare.local
    extraJwtKeyName: extraJwtKeyName
    ldapbaseDn: "ou=People,dc=linshare,dc=org"

  initDb:
    image: "docker-registry.linagora.com:5000/linshare-snapshots/linshare-database:4.0.0"

  # Parameters related to the thumbnail server
  thumbnail:
    enabled: true
    image: "docker-registry.linagora.com:5000/linshare-releases/linshare-thumbnail-server:2.1.1"
    replicaCount: 1
    resources:
      limits:
        cpu: "500m"
        memory: "500Mi"
      requests:
        cpu: "500m"
        memory: "500Mi"

# Global ingresses
ingress:
  enabled: false
  hosts:
    - host: linshare-admin.local
      path: "/"
      suffix: ui-admin
    - host: linshare-user.local
      paths: "/"
      suffix: ui-user

# Using LE
ingressRoutes:
  enabled: true
  baseDomain: &baseDomain example.org
  hosts:
    admin: linshare-admin.example.org
    user: linshare-user.example.org
    webmail: linshare-webmail.example.org
  tls:
    certResolver: resolvername
    domains:
      - main: *baseDomain
        sans:
          - "*.example.org"

# Using provided cert
ingressRoutes:
  enabled: true
  baseDomain: &baseDomain example.org
  hosts:
    admin: linshare-admin.example.org
    user: linshare-user.example.org
    webmail: linshare-webmail.example.org
  tls:
    secretName: example.org-cert-ddmmyyyy

# Database settings
mongodb:
  ips:
  - "1.2.3.4"
  - "4.5.6.7"
  
postgresql:
  port: "5432"
  ips:
  - "1.2.3.4"
  - "4.5.6.7"


# Additional parameters for demo purpose
demo:
  ldapAsPod: true
  mailServerAsPod: true
  mongodbAsPod: true
  postgresqlAsPod: true

  # DB settings
  mongodb:
    image: "mongo:4.2"
    storageSize: 2Gi
    storageClass: cinder-high-speed

  postgresql:
    image: "docker-registry.linagora.com:5000/linshare-snapshots/linshare-database:4.0.0"
    storageSize: 1Gi
    storageClass: cinder-high-speed

  # LDAP settings for demos
  ldap:
    image: "docker-registry.linagora.com:5000/linshare-releases/linshare-ldap-for-tests:1.0.1"

  # Mail settings for demos
  mail:
    image: "tvial/docker-mailserver:2.1"
  webmail:
    image: "robbertkl/roundcube"
