# Default values for linshare.

demo:
  enabled: true
  ldapAsPod: true
  mailServerAsPod: true
  mongodbAsPod: true

# enable deployment of ingresses.
ingress:
  enabled: "false"
  hosts:
    - host: linshare-admin.local
      path: "/"
      suffix: ui-admin
    - host: linshare-user.local
      paths: "/"
      suffix: ui-user

# enable deployment of traefik (v2) ingress routes
ingressroutes:
  enabled: "false"
  baseDomain: local
  certResolver: default
  hosts:
    admin: linshare-admin.local
    user: linshare-user.local
    webmail: linshare-webmail.local

mongodb:
  storageSize: 2Gi
  storageClass: cinder-classic
  image: "mongo:4.2"
    # ips:
  #   - "1.2.3.4"
  #   - "1.2.3.5"
  #   - "1.2.3.6"

postgresql:
  storageSize: 1Gi
  storageClass: cinder-classic
  image: "docker-registry.linagora.com:5000/linshare-snapshots/linshare-database:4.0.0"
  # ips:
  #   - "1.2.3.4"
  #   - "1.2.3.5"
  #   - "1.2.3.6"

backend:
  storageSize: 20Gi
  storageClass: cinder-classic
  ssoIpFilter: false
  profiles: default,jcloud,batches
  # profiles: sso,jcloud,batches
  thumbnail: true
  ##looking for a configmap with some extra keys to add to linshare.properties
  extraProperties: []
  #smtp: 127.0.0.1
  image: "docker-registry.linagora.com:5000/linshare-snapshots/linshare-backend:4.0.0"
  resources: {}
  # limits:
  #   cpu: "2"
  #   memory: "2Gi"
  # requests:
  #   cpu: "1"
  #   memory: "1Gi"


uiAdmin:
  externalUrl: null
  image: "docker-registry.linagora.com:5000/linshare-snapshots/linshare-ui-admin:4.0.0"

init:
  noReply: no-reply@linshare.local
  extraJwtKeyName: extraJwtKeyName
  image: "docker-registry.linagora.com:5000/linshare-releases/linshare-init:2.3.5"

uiUser:
  externalUrl: null
  image: "docker-registry.linagora.com:5000/linshare-snapshots/linshare-ui-user:4.0.0"

thumbnail:
  externalUrl: null
  image: "docker-registry.linagora.com:5000/linshare-releases/linshare-thumbnail-server:2.0.3"

# if you enable the demo mode, you may want to also deploy the ldap service too.
ldap:
  image: "docker-registry.linagora.com:5000/linshare-releases/linshare-ldap-for-tests:1.0.1"

mail:
  backend:
    image: "tvial/docker-mailserver:2.1"
  frontend:
    image: "robbertkl/roundcube"
