# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
{{- if .Values.demo.ldapAsPod }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linshare-ldap
  labels:
    {{- include "linshare.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linshare-ldap
      {{- include "linshare.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: linshare-ldap
        {{- include "linshare.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ldap
          image: {{ .Values.demo.ldap.image }}
          ports:
            - containerPort: 389
          resources:
            limits:
              cpu: "700m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
      {{- if .Values.dockerCredentials }}
      imagePullSecrets:
        - name: docker-registry-secret
      {{- end }}
{{- end }}
