# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
{{- if .Values.demo.ldapAsPod }}
apiVersion: v1
kind: Service
metadata:
  name: ldap
  labels:
    app: linshare-ldap
    {{- include "linshare.labels" . | nindent 4 }}
spec:
  ports:
    - name: '389'
      protocol: TCP
      port: 389
      targetPort: 1389
  selector:
    app: linshare-ldap
    {{- include "linshare.selectorLabels" . | nindent 4 }}
{{- end }}
