# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
{{- if .Values.demo.ldapAsPod }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linshare-ldap
  labels:
    {{- include "linshare.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linshare-ldap
      {{- include "linshare.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: linshare-ldap
        {{- include "linshare.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      {{- if .Values.demo.ldap.volumeName }}
        - name: ldap-data
          configMap:
            name: {{ .Values.demo.ldap.volumeName }}
      {{- end }}
      containers:
        - name: ldap
          image: {{ .Values.demo.ldap.image }}
          ports:
            - containerPort: 1389
          volumeMounts:
            {{- if .Values.demo.ldap.volumeName }}
            - name: ldap-data
              mountPath: /ldifs/linshare.ldif
              subPath: data.ldif
            {{- end }}
          resources:
            {{- toYaml .Values.demo.ldap.resources | nindent 12 }}
      {{- if .Values.dockerCredentials }}
      imagePullSecrets:
        - name: docker-registry-secret
      {{- end }}
{{- end }}
