# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linshare-thumbnail-server
  labels:
    {{- include "linshare.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.linshare.thumbnail.replicaCount }}
  selector:
    matchLabels:
      app: linshare-thumbnail-server
      {{- include "linshare.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: linshare-thumbnail-server
        {{- include "linshare.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: thumbnail-server
          image: {{ .Values.linshare.thumbnail.image }}
          resources:
            {{- toYaml .Values.linshare.thumbnail.resources | nindent 12 }}
          ports:
            - containerPort: 8080
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /ping
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 30
      {{- if .Values.dockerCredentials }}
      imagePullSecrets:
        - name: docker-registry-secret
      {{- end }}
