# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: db-postgresql-account-linshare
data:
{{- with .Values.postgresql.secret }}
  {{- if .username }}
  postgresql-username: {{ .username | b64enc }}
  {{- end }}
  {{- if .password }}
  postgresql-password: {{ .password | b64enc }}
  {{- end }}
  {{- if .dbName }}
  postgresql-database: {{ .dbName | b64enc }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: db-mongodb-account-linshare
data:
{{- with .Values.mongodb.secret }}
  {{- if .username }}
  mongodb-username: {{ .username | b64enc }}
  {{- end }}
  {{- if .password }}
  mongodb-password: {{ .password | b64enc }}
  {{- end }}
  {{- if .dbName }}
  mongodb-database: {{ .dbName | b64enc }}
  {{- end }}
  {{- if .dbName }}
  mongodb-small-files-database: {{ .dbNameForSmallFiles | b64enc }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: db-ldap-account-linshare
data:
{{- with .Values.linshare.init.secret }}
  {{- if .ldapUsername }}
  ldap-username: {{ .ldapUsername | b64enc }}
  {{- end }}
  {{- if .ldapPassword }}
  ldap-password: {{ .ldapPassword | b64enc }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: smtp-account-linshare
data:
{{- with .Values.linshare.backend.smtp.secret }}
  {{- if .username }}
  smtp-username: {{ .username | b64enc }}
  {{- end }}
  {{- if .password }}
  smtp-password: {{ .password | b64enc }}
  {{- end }}
{{- end }}
---
{{- if eq .Values.linshare.backend.storage.mode "openstack-swift" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: swift-linshare-credentials
data:
{{- with .Values.linshare.backend.storage.swift }}
  {{- if .bucketName }}
  STORAGE_BUCKET: {{ .bucketName | b64enc }}
  {{- end }}
  {{- if .authUrl }}
  OS_AUTH_URL: {{ .authUrl | b64enc }}
  {{- end }}
  {{- if .projectId }}
  OS_PROJECT_ID: {{ .projectId | b64enc }}
  {{- end }}
  {{- if .projectName }}
  OS_PROJECT_NAME: {{ .projectName | b64enc }}
  {{- end }}
  {{- if .userDomainName }}
  OS_USER_DOMAIN_NAME: {{ .userDomainName | b64enc }}
  {{- end }}
  {{- if .username }}
  OS_USERNAME: {{ .username | b64enc }}
  {{- end }}
  {{- if .password }}
  OS_PASSWORD: {{ .password | b64enc }}
  {{- end }}
  {{- if .regionName }}
  OS_REGION_NAME: {{ .regionName | b64enc }}
  {{- end }}
  {{- if .interface }}
  OS_INTERFACE: {{ .interface | b64enc }}
  {{- end }}
  {{- if .identityApiVersion }}
  OS_IDENTITY_API_VERSION: {{ .identityApiVersion | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: linshare-root-account
data:
  {{- if and .Values.linshare.init.secret .Values.linshare.init.secret.linshareRootPassword }}
  root-password: {{ .Values.linshare.init.secret.linshareRootPassword | b64enc }}
  {{- end }}
