# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linshare-ui-user
  labels:
    {{- include "linshare.labels" . | nindent 4 }}
  {{- if .Values.linshare.uiUser.annotations }}
  annotations:
{{ toYaml .Values.linshare.uiUser.annotations | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.linshare.uiUser.replicaCount }}
  selector:
    matchLabels:
      app: linshare-ui-user
      {{- include "linshare.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: linshare-ui-user
        {{- include "linshare.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      {{- if .Values.linshare.uiUser.jsConfigMapName }}
        - name: linshare-ui-user-js-config
          configMap:
            name: {{ .Values.linshare.uiUser.jsConfigMapName }}
      {{- end }}
      {{- if .Values.linshare.uiUser.resourcesConfigMapName }}
        - name: linshare-ui-user-resources
          configMap:
            name: {{ .Values.linshare.uiUser.resourcesConfigMapName }}
      {{- end }}
      containers:
        - name: ui-user
          image: {{ .Values.linshare.uiUser.image }}
          env:
          {{- if .Values.linshare.uiUser.externalUrl }}
            - name: EXTERNAL_URL
              value: {{ .Values.linshare.uiUser.externalUrl }}
          {{- end }}
            - name: TOMCAT_PORT
              value: '8080'
            - name: TOMCAT_URL
              value: linshare-backend
            - name: LINSHARE_THEME
              value: {{ .Values.linshare.uiUser.theme }}
          ports:
            - containerPort: 80
          volumeMounts:
            {{- if .Values.linshare.uiUser.jsConfigMapName }}
            - name: linshare-ui-user-js-config
              mountPath: /usr/local/apache2/htdocs/linshare-ui-user/config/config.js
              subPath: linshare.ui-user.config.js
            {{- end }}
            {{- if .Values.linshare.uiUser.resourcesConfigMapName }}
            - name: linshare-ui-user-resources
              mountPath: /usr/local/apache2/htdocs/linshare-ui-user/custom-resources
            {{- end }}
          resources:
            {{- toYaml .Values.linshare.uiUser.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
      {{- if .Values.dockerCredentials }}
      imagePullSecrets:
        - name: docker-registry-secret
      {{- end }}
