# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
{{- if .Values.demo.mailServerAsPod }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linshare-demo-mail
  labels:
    {{- include "linshare.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linshare-demo-mail
      {{- include "linshare.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: linshare-demo-mail
        {{- include "linshare.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: config
        configMap:
          name: linshare-demo-mail
      - name: config-web
        configMap:
          name: linshare-demo-webmail
      containers:
        - name: webmail
          image: {{ .Values.demo.webmail.image }}
          volumeMounts:
            - name: config-web
              mountPath: /var/www/config/config.inc.php
              subPath: config.inc.php
          env:
            - name: ROUNDCUBE_DEFAULT_HOST
              value: "localhost"
            - name: ROUNDCUBE_SMTP_SERVER
              value: "localhost"
            - name: ROUNDCUBE_SMTP_PORT
              value: "25"
          ports:
            - containerPort: 80
        - name: mail
          image: {{ .Values.demo.mail.image }}
          volumeMounts:
            - name: config
              mountPath: /etc/postfix/main.cf
              subPath: main.cf
            - name: config
              mountPath: /etc/dovecot/conf.d/10-ssl.conf
              subPath: 10-ssl.conf
            - name: config
              mountPath: /etc/dovecot/conf.d/10-auth.conf
              subPath: 10-auth.conf
            - name: config
              mountPath: /etc/dovecot/dovecot-ldap.conf.ext
              subPath: dovecot-ldap.conf.ext
          env:
            - name: ENABLE_SPAMASSASSIN
              value: "0"
            - name: ENABLE_CLAMAV
              value: "0"
            - name: ENABLE_FAIL2BAN
              value: "0"
            - name: ONE_DIR
              value: "1"
            - name: DMS_DEBUG
              value: "0"
            - name: ENABLE_LDAP
              value: "1"
            - name: OVERRIDE_HOSTNAME
              value: "mail.linshare.org"
            - name: HOSTNAME
              value: "mail"
            - name: DOMAINNAME
              value: "linshare.org"
            - name: LDAP_SERVER_HOST
              value: "ldap"
            - name: LDAP_SEARCH_BASE
              value: "ou=People,dc=linshare,dc=org"
            - name: LDAP_BIND_DN
              value: "cn=linshare,dc=linshare,dc=org"
            - name: LDAP_BIND_PW
              value: "linshare"
          ports:
            - containerPort: 25
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
            requests:
              cpu: "500m"
              memory: "500Mi"
      {{- if .Values.dockerCredentials }}
      imagePullSecrets:
        - name: docker-registry-secret
      {{- end }}
{{- end }}
