# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
{{- if .Values.demo.mongodbAsPod }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    {{- include "linshare.labels" . | nindent 4 }}
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      {{- include "linshare.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mongodb
        {{- include "linshare.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: {{ .Values.demo.mongodb.image }}
          imagePullPolicy: {{ .Values.demo.mongodb.imagePullPolicy }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-mongodb-account-linshare
                  key: mongodb-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-mongodb-account-linshare
                  key: mongodb-password
          ports:
            - containerPort: 27017
          resources:
            {{- toYaml .Values.demo.mongodb.resources | nindent 12 }}
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
      {{- if .Values.dockerCredentials }}
      imagePullSecrets:
        - name: docker-registry-secret
      {{- end }}
{{- if and (.Values.demo.mongodb.storageSize) (.Values.demo.mongodb.storageClass) }}
  volumeClaimTemplates:
    - metadata:
        annotations:
          volume.beta.kubernetes.io/storage-class: {{ .Values.demo.mongodb.storageClass }}
        name: mongodb-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.demo.mongodb.storageSize }}
{{- end }}
{{- end }}
