# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
{{- if .Values.mongodb.ips }}
apiVersion: v1
kind: Endpoints
metadata:
  name: mongodb
subsets:
  - addresses:
  {{- range $index, $ip := .Values.mongodb.ips }}
      - hostname: mongo-{{ $index }}
        ip: {{ $ip }}
  {{- end }}
    ports:
      - port: 27017
{{- end -}}
