# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
    {{- include "linshare.labels" . | nindent 4 }}
spec:
{{- if .Values.postgresql.externalName }}
  type: ExternalName
  externalName: {{ .Values.postgresql.externalName }}
{{- end -}}
{{- if not .Values.postgresql.externalName }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.port }}
{{- end -}}
{{- if and (not .Values.postgresql.ips) (not .Values.postgresql.externalName) }}
  selector:
    app: postgresql
    {{- include "linshare.selectorLabels" . | nindent 4 }}
{{- end -}}
