apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
spec:
  serviceName: "backend"
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
      - name: backend-extra-properties
        configMap:
          name: backend-extra-properties
      - name: jwt-keys
        secret:
          secretName: linshare-jwt-keys
          optional: true
      containers:
        - name: backend
          image: {{ .Values.backend.image | quote }}
          readinessProbe:
            httpGet:
              path: /linshare/
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /linshare/
              port: 8080
            initialDelaySeconds: 91
            periodSeconds: 30
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.backend.profiles }}"
            - name: SSO_IP_LIST_ENABLE
              value: "{{ .Values.backend.ssoIpFilter }}"
            - name: JAVA_XMX
              value: "2048m"
            - name: CLAMAV_HOST
              value: "1"
            - name: CLAMAV_PORT
              value: "3310"
            - name: MONGODB_DATA_REPLICA_SET
              value: "mongodb:27017"
            - name: MONGODB_SMALLFILES_REPLICA_SET
              value: "mongodb:27017"
            - name: POSTGRES_HOST
              value: "postgresql"
            - name: POSTGRES_PORT
              value: "5432"
	          {{- if .Values.backend.thumbnail }}
            - name: THUMBNAIL_ENABLE
              value: "true"
            - name: THUMBNAIL_HOST
              value: "thumbnail-server"
            {{- end }}
            {{- if eq .Values.demo.mailServerAsPod "true" }}
            - name: SMTP_HOST
              value: "mail"
            {{- else }}
            - name: SMTP_HOST
              value: "{{- required "A valid smpt host is required !" .Values.backend.smtp -}}"
            {{- end }}
            - name: SMTP_PORT
              value: "25"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-password
            - name: START_DEBUG
              value: "0"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: backend-extra-properties
              mountPath: /etc/linshare/linshare.extra.properties
              subPath: linshare.extra.properties
            - name: jwt-keys
              mountPath: /etc/linshare/private
              subPath: private
            - name: jwt-keys
              mountPath: /etc/linshare/public
              subPath: public
            - name: storage-filesystem
              mountPath: /var/lib/linshare/filesystemstorage
      imagePullSecrets:
        - name: docker-registry-secret
{{- if and (.Values.backend.storageSize) (.Values.backend.storageClass) }}
  volumeClaimTemplates:
    - metadata:
        annotations:
          volume.beta.kubernetes.io/storage-class: {{ .Values.backend.storageClass | quote }}
        name: storage-filesystem
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.backend.storageSize | quote }}
{{- end }}
