apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "linshare.labels" . | nindent 4 }}
    svc: linshare-backend
spec:
  ports:
    - protocol: TCP
      port: 8080
  selector:
    {{- include "linshare.selectorLabels" . | nindent 4 }}
    app: linshare-backend
