apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "database"
spec:
  serviceName: "database"
  replicas: 1
  selector:
    matchLabels:
      app: linshare-database
  template:
    metadata:
      labels:
        app: linshare-database
    spec:
      containers:
        - name: database
          image: {{ .Values.database.image | quote }}
          env:
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "linshare.database.secretName" . }}
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "linshare.database.secretName" . }}
                  key: postgres-password
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: "700m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: pg-data
    {{- if .Values.dockerCredentials }}
      imagePullSecrets:
        - name: docker-registry-secret
    {{- end }}
{{- if and (.Values.database.storageSize) (.Values.database.storageClass) }}
  volumeClaimTemplates:
    - metadata:
        annotations:
          volume.beta.kubernetes.io/storage-class: {{ .Values.database.storageClass | quote }}
        name: pg-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.database.storageSize | quote }}
{{- end }}
