apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    svc: linshare-database
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5432
  selector:
    app: linshare-database
