{{- if .Values.postgresql.secretName }}
{{ else }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgresql
  annotations:
    "helm.sh/resource-policy": keep
data:
  postgres-password: "{{ randAlphaNum 12 | b64enc }}"
  postgres-user: "{{ "linshare" | b64enc }}"
{{- end }}
