{{- if .Values.database.ips }}
apiVersion: v1
kind: Endpoints
metadata:
  name: database-endpoints
subsets:
  - addresses:
  {{- range $index, $ip := .Values.database.ips }}
      - hostname: database-{{ $index }}
        ip: {{ $ip }}
  {{- end }}
    ports:
      - port: 5432
{{- end -}}
