{{- if eq .Values.ingress.enabled "true" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: linshare
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .path }}
            backend:
              serviceName: linshare-{{.suffix}}
              servicePort: 80
  {{- end }}
{{- end }}
