# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
---
{{- if .Values.init.rootSecretName }}
{{ else }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "linshare.fullname" . }}-root-account
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    secret: linshare-root-account
{{ include "linshare.labels" . | indent 4 }}
data:
  root-password: "{{ randAlphaNum 16 | b64enc }}"
  root-user: "{{ "root@localhost.localdomain" | b64enc }}"
{{- end }}
