apiVersion: batch/v1
kind: Job
metadata:
  name: init
spec:
  activeDeadlineSeconds: 1800
  template:
    metadata:
      labels:
        app: linshare-init
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: extra-jwt-key
          secret:
            secretName: extra-jwt-key
            optional: true
      containers:
        - name: init
          image: {{ .Values.init.image }}
          volumeMounts:
            - name: extra-jwt-key
              mountPath: /linagora/data/
          env:
            - name: LS_DEBUG
              value: "0"
            - name: LS_SERVER_HOST
              value: backend
            - name: LS_SERVER_PORT
              value: "8080"
           {{- if .Values.uiUser.externalUrl }}
            - name: LS_USER_URL
              value: "{{ .Values.uiUser.externalUrl }}"
            - name: LS_EXTERNAL_URL
              value: "{{ .Values.uiUser.externalUrl }}"
           {{- end }}
            - name: LS_NO_REPLY_ADDRESS
              value: "{{ .Values.init.noReply }}"
           {{- if .Values.demo.enabled }}
            - name: LS_LDAP_NAME
              value: "ldap-demo"
            - name: LS_LDAP_URL
              value: "ldap://ldap:389"
            - name: LS_LDAP_BASE_DN
              value: "ou=People,dc=linshare,dc=org"
            - name: LS_LDAP_DN
              value: "cn=linshare,dc=linshare,dc=org"
            - name: LS_LDAP_PW
              value: "linshare"
            - name: LS_DEFAULT_PASSWORD
              value: "adminlinshare"
            - name: LS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: root-account
                  key: root-password
            - name: LS_DOMAIN_PATTERN_NAME
              value: "pattern-demo"
            - name: LS_DOMAIN_PATTERN_MODEL
              value: "a4620dfc-dc46-11e8-a098-2355f9d6585a"
            - name: LS_JWT_PUB_KEY_NAME
              value: "{{- .Values.init.extraJwtKeyName -}}"
            - name: LS_JWT_PUB_KEY
              value: "/linagora/data/public"
           {{- end }}
      imagePullSecrets:
        - name: docker-registry-secret
