# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
{{- if .Values.demo.ldapAsPod }}
apiVersion: v1
kind: Service
metadata:
  name: ldap
  labels:
    svc: linshare-ldap
spec:
  ports:
    - name: '389'
      protocol: TCP
      port: 389
      targetPort: 389
  selector:
    app: linshare-ldap
{{- end }}
