{{- if eq .Values.demo.ldapAsPod "true" }}
apiVersion: v1
kind: Service
metadata:
  name: ldap
  labels:
    svc: linshare-ldap
spec:
  ports:
    - name: '389'
      protocol: TCP
      port: 389
      targetPort: 389
  selector:
    app: linshare-ldap
{{- end }}
