{{- if eq .Values.ldap.deploy "true" }}
apiVersion: v1
kind: Service
metadata:
  name: ldap
  labels:
    {{- include "linshare.labels" . | nindent 4 }}
    svc: linshare-ldap
spec:
  ports:
    - name: '389'
      protocol: TCP
      port: 389
      targetPort: 389
  selector:
    {{- include "linshare.selectorLabels" . | nindent 4 }}
    app: linshare-ldap
{{- end }}
