{{- if eq .Values.ldap.deploy "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ldap"
  labels:
    {{- include "linshare.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "linshare.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "linshare.selectorLabels" . | nindent 8 }}
        app: linshare-ldap
    spec:
      containers:
        - name: ldap
          image: "{{ .Values.ldap.image.repository }}:{{ .Values.ldap.image.tag }}"
          imagePullPolicy: {{ .Values.ldap.image.pullPolicy }}
          ports:
            - containerPort: 389
          resources:
            limits:
              cpu: "700m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
    {{- if .Values.dockerRegistrySecret }}
      imagePullSecrets:
        - name: {{- .Values.dockerRegistrySecret }}
    {{- end }}
{{- end }}
