{{- if eq .Values.ldap.deploy "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ldap"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      linshare-ldap
  template:
    metadata:
      labels:
        app: linshare-ldap
    spec:
      containers:
        - name: ldap
          image: {{ .Values.ldap.image | quote }}
          ports:
            - containerPort: 389
          resources:
            limits:
              cpu: "700m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
    {{- if .Values.dockerRegistrySecret }}
      imagePullSecrets:
        - name: {{ .Values.dockerRegistrySecret }}
    {{- end }}
{{- end }}
