# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linshare-ui-user
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version \| replace "+" "_" }}"
    app.kubernetes.io/name: "{{- include "linshare.name" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.linshare.uiUser.replicaCount }}
  selector:
    matchLabels:
      app: linshare-ui-user
  template:
    metadata:
      labels:
        app: linshare-ui-user
    spec:
      containers:
        - name: ui-user
          image: {{ .Values.linshare.uiUser.image }}
          env:
          {{- if .Values.linshare.uiUser.externalUrl }}
            - name: EXTERNAL_URL
              value: {{ .Values.linshare.uiUser.externalUrl }}
          {{- end }}
            - name: TOMCAT_PORT
              value: '8080'
            - name: TOMCAT_URL
              value: linshare-backend
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
            requests:
              cpu: "500m"
              memory: "500Mi"
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
      {{- if .Values.dockerCredentials }}
      imagePullSecrets:
        - name: docker-registry-secret
      {{- end }}
