# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
apiVersion: v1
kind: Service
metadata:
  name: linshare-thumbnail-server
  labels:
    app: linshare-thumbnail-server
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version \| replace "+" "_" }}"
    app.kubernetes.io/name: "{{- include "linshare.name" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  ports:
    - name: '8080'
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: '8081'
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: linshare-thumbnail-server
