# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
apiVersion: v1
kind: Service
metadata:
  name: linshare-backend
  labels:
    app: linshare-backend
    {{- include "linshare.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 8080
  selector:
    app: linshare-backend
    {{- include "linshare.selectorLabels" . | nindent 4 }}
