{{- if .Values.demo.mailServerAsPod }}
apiVersion: v1
kind: Service
metadata:
  name: mail
  labels:
    svc: linshare-mail
spec:
  ports:
    - name: '25'
      protocol: TCP
      port: 25
      targetPort: 25
    - name: '80'
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: linshare-mail
{{- end }}
