# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
{{- if .Values.demo.mailServerAsPod }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mail
data:
  10-auth.conf: |
{{ .Files.Get "configs/10-auth.conf" | indent 4 }}
  10-ssl.conf: |
{{ .Files.Get "configs/10-ssl.conf" | indent 4 }}
  dovecot-ldap.conf.ext: |
{{ .Files.Get "configs/dovecot-ldap.conf.ext" | indent 4 }}
  main.cf: |
{{ .Files.Get "configs/main.cf" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webmail
data:
  config.inc.php: |-
{{ .Files.Get "configs/config.inc.php" | indent 4 }}
{{- end }}
