# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
{{- if .Values.demo.mongodbAsPod }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version \| replace "+" "_" }}"
    app.kubernetes.io/name: "{{- include "linshare.name" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: {{ .Values.demo.mongodb.image }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-mongodb-account-linshare
                  key: mongodb-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-mongodb-account-linshare
                  key: mongodb-password
          ports:
            - containerPort: 27017
          resources:
            limits:
              cpu: "700m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
      {{- if .Values.dockerCredentials }}
      imagePullSecrets:
        - name: docker-registry-secret
      {{- end }}
{{- if and (.Values.demo.mongodb.storageSize) (.Values.demo.mongodb.storageClass) }}
  volumeClaimTemplates:
    - metadata:
        annotations:
          volume.beta.kubernetes.io/storage-class: {{ .Values.demo.mongodb.storageClass }}
        name: mongodb-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.demo.mongodb.storageSize }}
{{- end }}
{{- end }}
