{{- if not .Values.mongodb.secretName }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongodb
  annotations:
    "helm.sh/resource-policy": keep
data:
  mongodb-password: "{{ randAlphaNum 12 | b64enc }}"
  mongodb-user: "{{ "linshare" | b64enc }}"
{{- end }}
