{{- if eq .Values.mongodb.deploy "true"}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: linshare-mongodb
  template:
    metadata:
      labels:
        app: linshare-mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: {{ .Values.mongodb.image | quote }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "linshare.mongodb.secretName" . }}
                  key: mongodb-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "linshare.mongodb.secretName" . }}
                  key: mongodb-password
          ports:
            - containerPort: 27017
          resources:
            limits:
              cpu: "700m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
    {{- if .Values.dockerCredentials }}
      imagePullSecrets:
        - name: docker-registry-secret
    {{- end }}
{{- if and (.Values.mongodb.storageSize) (.Values.mongodb.storageClass) }}
  volumeClaimTemplates:
    - metadata:
        annotations:
          volume.beta.kubernetes.io/storage-class: {{ .Values.mongodb.storageClass | quote }}
        name: mongodb-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.mongodb.storageSize | quote }}
{{- end }}
{{- end }}