{{- if .Values.demo.mongodbAsPod }}
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - protocol: TCP
      port: 27017
  selector:
    app: mongodb
{{- end }}