# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.port }}
{{- if not .Values.postgresql.ips }}
  selector:
    app: postgresql
{{- end -}}
