# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version \| replace "+" "_" }}"
    app.kubernetes.io/name: "{{- include "linshare.name" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.port }}