# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    svc: postgresql
spec:
  ports:
    - protocol: TCP
      port: 5432
  selector:
    app: postgresql
