{{- if .Values.postgresql.ips }}
apiVersion: v1
kind: Endpoints
metadata:
  name: postgresql-endpoints
subsets:
  - addresses:
  {{- range $index, $ip := .Values.postgresql.ips }}
      - hostname: postgresql-{{ $index }}
        ip: {{ $ip }}
  {{- end }}
    ports:
      - port: 5432
{{- end -}}
