# vim: syntax=yaml textwidth=80 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnail-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: linshare-thumbnail-server
  template:
    metadata:
      labels:
        app: linshare-thumbnail-server
    spec:
      containers:
        - name: thumbnail-server
          image: {{ .Values.thumbnail.image }}
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
            requests:
              cpu: "500m"
              memory: "500Mi"
          ports:
            - containerPort: 8080
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /ping
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 30
      imagePullSecrets:
        - name: docker-registry-secret
