apiVersion: v1
kind: Service
metadata:
  name: thumbnail-server
  labels:
    svc: linshare-thumbnail-server
spec:
  ports:
    - name: '8080'
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: '8081'
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: linshare-thumbnail-server
