apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnail-server
  labels:
    {{- include "linshare.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "linshare.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "linshare.selectorLabels" . | nindent 8 }}
        app: linshare-thumbnail-server
    spec:
      containers:
        - name: thumbnail-server
          image: {{ .Values.thumbnail.image }}
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
            requests:
              cpu: "500m"
              memory: "500Mi"
          ports:
            - containerPort: 8080
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /ping
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 30
    {{- if .Values.dockerCredentials }}
      imagePullSecrets:
        - name: docker-registry-secret
    {{- end }}
