apiVersion: v1
kind: Service
metadata:
  name: ui-admin
  labels:
    svc: linshare-ui-admin
spec:
  ports:
    - name: '80'
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: linshare-ui-admin
