apiVersion: v1
kind: Service
metadata:
  name: ui-user
  labels:
    svc: linshare-ui-user
spec:
  ports:
    - name: '80'
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: linshare-ui-user
