apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-user
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: linshare-ui-user
  template:
    metadata:
      labels:
        app: linshare-ui-user
    spec:
      containers:
        - name: ui-user
          image: {{ .Values.uiUser.image }}
          env:
          {{- if .Values.uiUser.externalUrl }}
            - name: EXTERNAL_URL
              value: {{ .Values.uiUser.externalUrl }}
          {{- end }}
            - name: TOMCAT_PORT
              value: '8080'
            - name: TOMCAT_URL
              value: backend
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
            requests:
              cpu: "500m"
              memory: "500Mi"
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
      imagePullSecrets:
        - name: docker-registry-secret
